#
# unlock-reopened.yml
# Unlock an issue whenever it is re-opened
#

name: Unlock Reopened Issue

on:
  issues:
    types: [reopened]

jobs:
  unlock:
    name: Unlock Reopened Issues
    if: github.repository == 'OctoPrint/OctoPrint-FirmwareUpdater'

    runs-on: ubuntu-latest

    steps:
    - uses: OSDKDev/unlock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
